import Head from 'next/head';
import { Welcome, WhatWeDo } from '../components/Sections/';

export default function Home() {
  return (
    <div>
      <Head>
        <title>PMM Edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <WhatWeDo />
    </div>
  );
}
